### PR TITLE
Korean Translation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by bkcsoft** [comment]
LGTM

(Checked using Gtranslate. Can't vouch for the correctness of the translation, but at least the content seems to be right)

**Comment by lunny** [comment]
but the author has been deleted.

**Comment by bkcsoft** [comment]
@lunny We can still merge it though :thinking:

**Comment by AlexKoala** [comment]
PR abandoned?

**Comment by AlexKoala** [comment]
LGTM

**Comment by AlexKoala** [comment]
a

**Pull request closed without merging**
