### PR TITLE
Automatically copy missing translations

### LINKED ISSUE #20: Integrate a translation copy script
We should integrate a script like https://github.com/drone/drone-plugin-index/blob/master/scripts/gen-language-content.go that enforces that all documents are available in all translations.

### PR DESCRIPTION
**Pull request by tboerger**
Fixes #20

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by appleboy** [comment]
LGTM

**Comment by lunny** [comment]
@appleboy you have to use English characters.

**Comment by appleboy** [comment]
@lunny Done!

**Pull request merged**
