### PR TITLE
Build caddy with plugin

### LINKED ISSUE #42: Build of container failed
Same as go-gitea/docs#120

https://drone.gitea.io/go-gitea/website/133

### PR DESCRIPTION
**Pull request by sapk**
With a multi-stage Dockerfile. 

Fix #42

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by sapk** [comment]
As this is a multistage Dockerfile, this will maybe need to force update of image plugin/docker by using tag 17:05. I will make this in another PR if needed as I couldn't find the version currently running on drone.gitea.io

**Comment by appleboy** [comment]
@sapk See https://github.com/go-gitea/website/pull/45

**Comment by Bwko** [comment]
LGTM

**Pull request merged**
